export const items = [
  {
    id: Math.random(),
    title: "House 1",
    bedrooms: 3,
    bathrooms: 1,
    floors: 1,
    sqft: "sqft: 1180",
    grade: "7",
    sqft_above: ' 1180',
    basement: ' 0',
    population: '24092',
    img: "house1.jpeg",
    category: "3 Bedrooms",
  },
  {
    id: Math.random(),
    title: "House 2",
    bedrooms: 3,
    bathrooms: 2,
    floors: 2,
    sqft: "sqft: 2570",
    grade: "7",
    sqft_above: ' 2170',
    basement: ' 400',
    population: '37081',
    img: "house2.jpeg",
    category: "3 Bedrooms",
  },
  {
    id: Math.random(),
    title: "House 3",
    bedrooms: 2,
    bathrooms: 1,
    floors: 1,
    sqft: "sqft: 770",
    grade: "6",
    sqft_above: '770',
    basement: '0',
    population: '20419',
    img: "house3.jpeg",
    category: "2 Bedrooms",
  },
  {
    id: Math.random(),
    title: "House 4",
    bedrooms: 4,
    bathrooms: 1,
    floors: 1,
    sqft: "sqft: 1960",
    grade: "7",
    sqft_above: '1050',
    basement: '910',
    population: '14770',
    img: "house4.jpeg",
    category: "4 Bedrooms",
  },
  {
    id: Math.random(),
    title: "House 5",
    bedrooms: 3,
    bathrooms: 1,
    floors: 1,
    sqft: "sqft: 1680",
    grade: "8",
    sqft_above: '1680',
    basement: '0',
    population: '25748',
    img: "house5.jpeg",
    category: "3 Bedrooms",
  },
  {
    id: Math.random(),
    category: "2 Bedrooms",
  },
  {
    id: Math.random(),
    category: "4 Bedrooms",
  }
];
