export const items = [
  {
    id: Math.random(),
    title: "Breakfast Meal",
    description: "This is a longer card with supporting text below ",
    price: "50$",
    img: "breakfast1.webp",
    category: "Breakfast",
  },
  {
    id: Math.random(),
    title: "Lunch Meal",
    description: "This is a longer card with supporting text below ",
    price: "100$",
    img: "lunch1.webp",
    category: "Lunch",
  },
  {
    id: Math.random(),
    title: "Lunch Meal",
    description: "This is a longer card with supporting text below ",
    price: "100$",
    img: "lunch2.webp",
    category: "Lunch",
  },
  {
    id: Math.random(),
    title: "Dinner Meal",
    description: "This is a longer card with supporting text below ",
    price: "25$",
    img: "dinner1.webp",
    category: "Dinner",
  },
  {
    id: Math.random(),
    title: "Breakfast Meal",
    description: "This is a longer card with supporting text below ",
    price: "90$",
    img: "breakfast2.webp",
    category: "Breakfast",
  },
  {
    id: Math.random(),
    title: "Dinner Meal",
    description: "This is a longer card with supporting text below ",
    price: "40$",
    img: "dinner2.webp",
    category: "Dinner",
  },
  // {
  //   id: Math.random(),
  //   title: "Dinner Meal",
  //   description: "This is a longer card with supporting text below ",
  //   price: "40$",
  //   img: "breakfast3.webp",
  //   category: "Snack",
  // },
];
